name: lakoni
favicon: null
layout_spectrum: 0.527214489178732
typography_spectrum: 0.7635341899003834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3977933661080897
  lightness: 0.2082017557695508
  saturation: 0.7916911521460861
  rhythmicContrast: 0.17410018318332732
purpose: []
